#!/bin/sh

# SPDX-FileCopyrightText: 2020 Nerves Project Developers
#
# SPDX-License-Identifier: Apache-2.0

#
# Lego EV3 auto-detected
#

cat >$WORK/proc/cpuinfo <<EOF
processor	: 0
model name	: ARM926EJ-S rev 5 (v5l)
BogoMIPS	: 148.88
Features	: swp half thumb fastmult edsp java
CPU implementer	: 0x41
CPU architecture: 5TEJ
CPU variant	: 0x0
CPU part	: 0x926
CPU revision	: 5

Hardware	: LEGO MINDSTORMS EV3 Programmable Brick
Revision	: 0006
Serial		: 00000016534b129d
EOF

CMDLINE=""

cat >$EXPECTED <<EOF
00000016534b129d
EOF
