#!/bin/sh
# SPDX-FileCopyrightText: 2016 Frank Hunleth
#
# SPDX-License-Identifier: Apache-2.0

#
# MAC Address w/ 4 digits
#

cat >$WORK/sys/class/net/eth0/address <<EOF
11:22:33:44:55:66
EOF

CMDLINE="-b macaddr"

cat >$EXPECTED <<EOF
112233445566
EOF
