#!/bin/sh
# SPDX-FileCopyrightText: 2018 Frank Hunleth
#
# SPDX-License-Identifier: Apache-2.0

#
# Force an ID and truncate it to 4 digits
#

CMDLINE="-b force -f 0123456789 -n 4"

cat >$EXPECTED <<EOF
0123
EOF
