#!/bin/sh

#
# Verify that STM32MP1 serial numbers work. They're 24 hex digits long
# which makes them longer than most other devices.
#

cat >$WORK/proc/cpuinfo <<EOF
processor	: 0
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 48.00
Features	: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 1
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 48.00
Features	: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

Hardware	: STM32 (Device Tree Support)
Revision	: 0000
Serial		: 0032001C3338510934383330
EOF

CMDLINE="-b cpuinfo"

cat >$EXPECTED <<EOF
0032001C3338510934383330
EOF
