#!/bin/sh

#
# Raspberry Pi 4 eth0 MAC address
#

cat >$WORK/proc/cpuinfo <<EOF
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 2.00
Features	: half thumb fastmult vfp edsp java tls
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2708
Revision	: 000e
Serial		: 0000000019f2f468
EOF

CMDLINE="-b rpi4_eth0"

cat >$EXPECTED <<EOF
dca632f2f468
EOF
