#!/bin/sh

# SPDX-FileCopyrightText: 2023 Nerves Project Developers
#
# SPDX-License-Identifier: Apache-2.0

#
# Script
#

cat >$WORK/etc/my_serial <<EOF
#!/bin/sh

printf "12345678"
EOF
chmod +x $WORK/etc/my_serial

CMDLINE="-b script -f $WORK/etc/my_serial"

cat >$EXPECTED <<EOF
12345678
EOF
