version: 2.1

jobs:
  check-license:
    docker:
      - image: fsfe/reuse:latest
    steps:
      - checkout
      - run: reuse lint

  build:
    docker:
      - image: cimg/base:2025.03

    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y xxd
      - run: make
      - run: make check

workflows:
  checks:
    jobs:
      - check-license:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
